import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import SocketProvider from '@/components/socket-provider';
import ActionButtons from '@/components/action-buttons';
import { JSX } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const isDev = process.env.NODE_ENV === 'development';

// Default no-op component for prod
let JotaiDevtools: () => JSX.Element | null = () => null;

if (isDev) {
  // Require devtools only in dev mode
  // @ts-ignore
  JotaiDevtools = require('@/components/jotai-devtools').default;
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <SocketProvider />
            {/* This will render only in development */}
            <JotaiDevtools />
            <main className="w-full p-4">
              <ActionButtons />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
