import { columns } from '@/components/table/columns';
import { DataTable } from '@/components/table/data-table';
import { Torrent } from '@/types/Torrent';

export default function AllPage() {
    const data: Torrent[] = [
        {
            name: 'Ubuntu ISO',
            files: [
                {
                    name: 'ubuntu.iso',
                    length: 2_500_000_000,
                    downloaded: 1_200_000_000,
                    progress: 0.48,
                    path: '/isos/ubuntu.iso',
                },
            ],
            infoHash: 'hash0001',
            totalSize: 2_500_000_000,
            numFiles: 1,
            progress: 0.48,
            downloaded: 1_200_000_000,
            total: 2_500_000_000,
            downloadSpeed: 1_000_000,
            numPeers: 8,
            peers: [
                {
                    ipAddress: '10.0.0.1',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'uTorrent',
                    progress: 0.8,
                    downloadSpeed: 300_000,
                    uploadSpeed: 100_000,
                    downloaded: 2_000_000_000,
                    uploaded: 100_000_000,
                    relevance: 0.9,
                },
                {
                    ipAddress: '10.0.0.2',
                    port: 6882,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'qBittorrent',
                    progress: 0.6,
                    downloadSpeed: 200_000,
                    uploadSpeed: 50_000,
                    downloaded: 1_500_000_000,
                    uploaded: 60_000_000,
                    relevance: 0.6,
                },
            ],
        },
        {
            name: 'Movie Collection',
            files: [
                {
                    name: 'movie1.mkv',
                    length: 700_000_000,
                    downloaded: 700_000_000,
                    progress: 1,
                    path: '/movies/movie1.mkv',
                },
                {
                    name: 'movie2.mkv',
                    length: 1_200_000_000,
                    downloaded: 600_000_000,
                    progress: 0.5,
                    path: '/movies/movie2.mkv',
                },
            ],
            infoHash: 'hash0002',
            totalSize: 1_900_000_000,
            numFiles: 2,
            progress: 0.68,
            downloaded: 1_300_000_000,
            total: 1_900_000_000,
            downloadSpeed: 2_000_000,
            numPeers: 5,
            peers: [
                {
                    ipAddress: '192.168.1.10',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 100_000,
                    downloaded: 1_900_000_000,
                    uploaded: 200_000_000,
                    relevance: 1,
                },
                {
                    ipAddress: '192.168.1.11',
                    port: 51414,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'qBittorrent',
                    progress: 0.7,
                    downloadSpeed: 500_000,
                    uploadSpeed: 50_000,
                    downloaded: 1_330_000_000,
                    uploaded: 80_000_000,
                    relevance: 0.7,
                },
            ],
        },
        {
            name: 'Open Source Code',
            files: [
                {
                    name: 'project.zip',
                    length: 50_000_000,
                    downloaded: 50_000_000,
                    progress: 1,
                    path: '/projects/project.zip',
                },
            ],
            infoHash: 'hash0003',
            totalSize: 50_000_000,
            numFiles: 1,
            progress: 1,
            downloaded: 50_000_000,
            total: 50_000_000,
            downloadSpeed: 0,
            numPeers: 3,
            peers: [
                {
                    ipAddress: '172.16.0.5',
                    port: 6000,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'uTorrent',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 5_000,
                    downloaded: 50_000_000,
                    uploaded: 5_000_000,
                    relevance: 1,
                },
                {
                    ipAddress: '172.16.0.6',
                    port: 6001,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 4_000,
                    downloaded: 50_000_000,
                    uploaded: 4_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'Linux Kernel',
            files: [
                {
                    name: 'linux.tar.gz',
                    length: 100_000_000,
                    downloaded: 90_000_000,
                    progress: 0.9,
                    path: '/kernels/linux.tar.gz',
                },
            ],
            infoHash: 'hash0004',
            totalSize: 100_000_000,
            numFiles: 1,
            progress: 0.9,
            downloaded: 90_000_000,
            total: 100_000_000,
            downloadSpeed: 500_000,
            numPeers: 4,
            peers: [
                {
                    ipAddress: '8.8.8.8',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'qBittorrent',
                    progress: 0.9,
                    downloadSpeed: 500_000,
                    uploadSpeed: 100_000,
                    downloaded: 90_000_000,
                    uploaded: 30_000_000,
                    relevance: 0.9,
                },
                {
                    ipAddress: '8.8.4.4',
                    port: 6882,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 40_000,
                    downloaded: 100_000_000,
                    uploaded: 40_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'Game Update',
            files: [
                {
                    name: 'game_patch.zip',
                    length: 1_200_000_000,
                    downloaded: 400_000_000,
                    progress: 0.33,
                    path: '/games/game_patch.zip',
                },
            ],
            infoHash: 'hash0005',
            totalSize: 1_200_000_000,
            numFiles: 1,
            progress: 0.33,
            downloaded: 400_000_000,
            total: 1_200_000_000,
            downloadSpeed: 1_500_000,
            numPeers: 6,
            peers: [
                {
                    ipAddress: '203.0.113.1',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'uTorrent',
                    progress: 0.5,
                    downloadSpeed: 600_000,
                    uploadSpeed: 80_000,
                    downloaded: 600_000_000,
                    uploaded: 50_000_000,
                    relevance: 0.6,
                },
                {
                    ipAddress: '203.0.113.2',
                    port: 51414,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'qBittorrent',
                    progress: 0.2,
                    downloadSpeed: 200_000,
                    uploadSpeed: 30_000,
                    downloaded: 240_000_000,
                    uploaded: 15_000_000,
                    relevance: 0.3,
                },
            ],
        },

        // 15 more similar mock torrent objects:
        {
            name: 'Music Album',
            files: [
                {
                    name: 'album.zip',
                    length: 100_000_000,
                    downloaded: 100_000_000,
                    progress: 1,
                    path: '/music/album.zip',
                },
            ],
            infoHash: 'hash0006',
            totalSize: 100_000_000,
            numFiles: 1,
            progress: 1,
            downloaded: 100_000_000,
            total: 100_000_000,
            downloadSpeed: 0,
            numPeers: 3,
            peers: [
                {
                    ipAddress: '192.168.0.5',
                    port: 6000,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 10_000,
                    downloaded: 100_000_000,
                    uploaded: 10_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'Ebook Collection',
            files: [
                {
                    name: 'ebooks.zip',
                    length: 300_000_000,
                    downloaded: 150_000_000,
                    progress: 0.5,
                    path: '/ebooks/ebooks.zip',
                },
            ],
            infoHash: 'hash0007',
            totalSize: 300_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 150_000_000,
            total: 300_000_000,
            downloadSpeed: 600_000,
            numPeers: 4,
            peers: [
                {
                    ipAddress: '192.168.0.6',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'uTorrent',
                    progress: 0.5,
                    downloadSpeed: 600_000,
                    uploadSpeed: 60_000,
                    downloaded: 150_000_000,
                    uploaded: 6_000_000,
                    relevance: 0.6,
                },
            ],
        },
        {
            name: 'Documentaries',
            files: [
                {
                    name: 'doc1.mp4',
                    length: 1_000_000_000,
                    downloaded: 1_000_000_000,
                    progress: 1,
                    path: '/docs/doc1.mp4',
                },
            ],
            infoHash: 'hash0008',
            totalSize: 1_000_000_000,
            numFiles: 1,
            progress: 1,
            downloaded: 1_000_000_000,
            total: 1_000_000_000,
            downloadSpeed: 0,
            numPeers: 2,
            peers: [
                {
                    ipAddress: '10.1.1.1',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 20_000,
                    downloaded: 1_000_000_000,
                    uploaded: 20_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'Software Suite',
            files: [
                {
                    name: 'software_setup.exe',
                    length: 600_000_000,
                    downloaded: 600_000_000,
                    progress: 1,
                    path: '/software/software_setup.exe',
                },
            ],
            infoHash: 'hash0009',
            totalSize: 600_000_000,
            numFiles: 1,
            progress: 1,
            downloaded: 600_000_000,
            total: 600_000_000,
            downloadSpeed: 0,
            numPeers: 7,
            peers: [
                {
                    ipAddress: '172.16.5.5',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'qBittorrent',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 15_000,
                    downloaded: 600_000_000,
                    uploaded: 15_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'Anime Series',
            files: [
                {
                    name: 'episode1.mkv',
                    length: 300_000_000,
                    downloaded: 100_000_000,
                    progress: 0.33,
                    path: '/anime/episode1.mkv',
                },
                {
                    name: 'episode2.mkv',
                    length: 320_000_000,
                    downloaded: 160_000_000,
                    progress: 0.5,
                    path: '/anime/episode2.mkv',
                },
            ],
            infoHash: 'hash0010',
            totalSize: 620_000_000,
            numFiles: 2,
            progress: 0.42,
            downloaded: 260_000_000,
            total: 620_000_000,
            downloadSpeed: 800_000,
            numPeers: 6,
            peers: [
                {
                    ipAddress: '203.0.114.5',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'uTorrent',
                    progress: 0.6,
                    downloadSpeed: 400_000,
                    uploadSpeed: 50_000,
                    downloaded: 370_000_000,
                    uploaded: 40_000_000,
                    relevance: 0.7,
                },
            ],
        },
        {
            name: 'Photography Portfolio',
            files: [
                {
                    name: 'photos.zip',
                    length: 1_000_000_000,
                    downloaded: 1_000_000_000,
                    progress: 1,
                    path: '/photos/photos.zip',
                },
            ],
            infoHash: 'hash0011',
            totalSize: 1_000_000_000,
            numFiles: 1,
            progress: 1,
            downloaded: 1_000_000_000,
            total: 1_000_000_000,
            downloadSpeed: 0,
            numPeers: 3,
            peers: [
                {
                    ipAddress: '10.10.10.10',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 25_000,
                    downloaded: 1_000_000_000,
                    uploaded: 25_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'Classic Movies',
            files: [
                {
                    name: 'classic1.mkv',
                    length: 800_000_000,
                    downloaded: 600_000_000,
                    progress: 0.75,
                    path: '/classics/classic1.mkv',
                },
                {
                    name: 'classic2.mkv',
                    length: 900_000_000,
                    downloaded: 450_000_000,
                    progress: 0.5,
                    path: '/classics/classic2.mkv',
                },
            ],
            infoHash: 'hash0012',
            totalSize: 1_700_000_000,
            numFiles: 2,
            progress: 0.62,
            downloaded: 1_050_000_000,
            total: 1_700_000_000,
            downloadSpeed: 1_200_000,
            numPeers: 4,
            peers: [
                {
                    ipAddress: '192.168.100.10',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'qBittorrent',
                    progress: 0.8,
                    downloadSpeed: 600_000,
                    uploadSpeed: 60_000,
                    downloaded: 1_360_000_000,
                    uploaded: 80_000_000,
                    relevance: 0.9,
                },
            ],
        },
        {
            name: 'Tech Tutorials',
            files: [
                {
                    name: 'tutorials.zip',
                    length: 250_000_000,
                    downloaded: 125_000_000,
                    progress: 0.5,
                    path: '/tutorials/tutorials.zip',
                },
            ],
            infoHash: 'hash0013',
            totalSize: 250_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 125_000_000,
            total: 250_000_000,
            downloadSpeed: 400_000,
            numPeers: 5,
            peers: [
                {
                    ipAddress: '10.0.1.2',
                    port: 6881,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'uTorrent',
                    progress: 0.5,
                    downloadSpeed: 400_000,
                    uploadSpeed: 40_000,
                    downloaded: 125_000_000,
                    uploaded: 12_000_000,
                    relevance: 0.5,
                },
            ],
        },
        {
            name: 'VR Game',
            files: [
                {
                    name: 'vrgame.zip',
                    length: 3_000_000_000,
                    downloaded: 1_500_000_000,
                    progress: 0.5,
                    path: '/games/vrgame.zip',
                },
            ],
            infoHash: 'hash0014',
            totalSize: 3_000_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 1_500_000_000,
            total: 3_000_000_000,
            downloadSpeed: 2_500_000,
            numPeers: 10,
            peers: [
                {
                    ipAddress: '203.0.115.1',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'qBittorrent',
                    progress: 0.6,
                    downloadSpeed: 1_000_000,
                    uploadSpeed: 100_000,
                    downloaded: 1_800_000_000,
                    uploaded: 150_000_000,
                    relevance: 0.7,
                },
            ],
        },
        {
            name: 'Photography Workshop',
            files: [
                {
                    name: 'workshop.pdf',
                    length: 20_000_000,
                    downloaded: 20_000_000,
                    progress: 1,
                    path: '/workshops/workshop.pdf',
                },
            ],
            infoHash: 'hash0015',
            totalSize: 20_000_000,
            numFiles: 1,
            progress: 1,
            downloaded: 20_000_000,
            total: 20_000_000,
            downloadSpeed: 0,
            numPeers: 2,
            peers: [
                {
                    ipAddress: '192.168.1.20',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'Transmission',
                    progress: 1,
                    downloadSpeed: 0,
                    uploadSpeed: 2_000,
                    downloaded: 20_000_000,
                    uploaded: 2_000_000,
                    relevance: 1,
                },
            ],
        },
        {
            name: 'TV Series',
            files: [
                {
                    name: 'season1_ep1.mkv',
                    length: 500_000_000,
                    downloaded: 400_000_000,
                    progress: 0.8,
                    path: '/tv/season1_ep1.mkv',
                },
                {
                    name: 'season1_ep2.mkv',
                    length: 520_000_000,
                    downloaded: 260_000_000,
                    progress: 0.5,
                    path: '/tv/season1_ep2.mkv',
                },
            ],
            infoHash: 'hash0016',
            totalSize: 1_020_000_000,
            numFiles: 2,
            progress: 0.64,
            downloaded: 660_000_000,
            total: 1_020_000_000,
            downloadSpeed: 700_000,
            numPeers: 6,
            peers: [
                {
                    ipAddress: '10.10.1.10',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'uTorrent',
                    progress: 0.6,
                    downloadSpeed: 400_000,
                    uploadSpeed: 30_000,
                    downloaded: 612_000_000,
                    uploaded: 40_000_000,
                    relevance: 0.6,
                },
            ],
        },
        {
            name: 'Language Learning',
            files: [
                {
                    name: 'spanish_course.zip',
                    length: 150_000_000,
                    downloaded: 75_000_000,
                    progress: 0.5,
                    path: '/courses/spanish_course.zip',
                },
            ],
            infoHash: 'hash0017',
            totalSize: 150_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 75_000_000,
            total: 150_000_000,
            downloadSpeed: 300_000,
            numPeers: 4,
            peers: [
                {
                    ipAddress: '172.20.10.5',
                    port: 6000,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'Transmission',
                    progress: 0.5,
                    downloadSpeed: 300_000,
                    uploadSpeed: 25_000,
                    downloaded: 75_000_000,
                    uploaded: 10_000_000,
                    relevance: 0.5,
                },
            ],
        },
        {
            name: 'Photography Portfolio Vol 2',
            files: [
                {
                    name: 'photos_v2.zip',
                    length: 900_000_000,
                    downloaded: 450_000_000,
                    progress: 0.5,
                    path: '/photos/photos_v2.zip',
                },
            ],
            infoHash: 'hash0018',
            totalSize: 900_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 450_000_000,
            total: 900_000_000,
            downloadSpeed: 800_000,
            numPeers: 5,
            peers: [
                {
                    ipAddress: '192.168.10.5',
                    port: 51413,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'qBittorrent',
                    progress: 0.5,
                    downloadSpeed: 800_000,
                    uploadSpeed: 70_000,
                    downloaded: 450_000_000,
                    uploaded: 50_000_000,
                    relevance: 0.5,
                },
            ],
        },
        {
            name: 'Math Lectures',
            files: [
                {
                    name: 'lecture1.mp4',
                    length: 700_000_000,
                    downloaded: 350_000_000,
                    progress: 0.5,
                    path: '/lectures/lecture1.mp4',
                },
            ],
            infoHash: 'hash0019',
            totalSize: 700_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 350_000_000,
            total: 700_000_000,
            downloadSpeed: 500_000,
            numPeers: 3,
            peers: [
                {
                    ipAddress: '10.0.0.10',
                    port: 6881,
                    connectionType: 'TCP',
                    flags: 'D',
                    client: 'Transmission',
                    progress: 0.5,
                    downloadSpeed: 500_000,
                    uploadSpeed: 40_000,
                    downloaded: 350_000_000,
                    uploaded: 30_000_000,
                    relevance: 0.5,
                },
            ],
        },
        {
            name: 'Open Movie Project',
            files: [
                {
                    name: 'openmovie.mp4',
                    length: 2_000_000_000,
                    downloaded: 1_000_000_000,
                    progress: 0.5,
                    path: '/openmovie/openmovie.mp4',
                },
            ],
            infoHash: 'hash0020',
            totalSize: 2_000_000_000,
            numFiles: 1,
            progress: 0.5,
            downloaded: 1_000_000_000,
            total: 2_000_000_000,
            downloadSpeed: 1_000_000,
            numPeers: 7,
            peers: [
                {
                    ipAddress: '192.168.1.30',
                    port: 51413,
                    connectionType: 'uTP',
                    flags: 'E',
                    client: 'uTorrent',
                    progress: 0.5,
                    downloadSpeed: 1_000_000,
                    uploadSpeed: 90_000,
                    downloaded: 1_000_000_000,
                    uploaded: 80_000_000,
                    relevance: 0.5,
                },
            ],
        },
    ];

    return (
        <DataTable columns={columns} data={data as unknown as Array<Torrent>} />
    );
}
